name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
        
     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: dotnet nuget add source ${{ secrets.GG_NUGET_SOURCE_URL }} -n ggroupp -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }} -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }} --store-password-in-clear-text

    # Http.SocketsHandlerProvider.Abstractions
    
    - name: Restore Http.SocketsHandlerProvider.Abstractions
      run: dotnet restore ./src/*/Http.SocketsHandlerProvider.Abstractions.csproj

    - name: Build Http.SocketsHandlerProvider.Abstractions
      run: dotnet build ./src/*/Http.SocketsHandlerProvider.Abstractions.csproj --no-restore  -c Release

    - name: Pack Http.SocketsHandlerProvider.Abstractions
      run: dotnet pack ./src/*/Http.SocketsHandlerProvider.Abstractions.csproj --no-restore -o ~/nuget  -c Release
      
    # Http.SocketsHandlerProvider

    - name: Restore Http.SocketsHandlerProvider
      run: dotnet restore ./src/*/Http.SocketsHandlerProvider.csproj

    - name: Build Http.SocketsHandlerProvider
      run: dotnet build ./src/*/Http.SocketsHandlerProvider.csproj --no-restore  -c Release

    - name: Pack Http.SocketsHandlerProvider
      run: dotnet pack ./src/*/Http.SocketsHandlerProvider.csproj --no-restore -o ~/nuget  -c Release
      
    # Push
      
    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet nuget push "../../../nuget/*.nupkg" -s ${{ secrets.GG_NUGET_SOURCE_URL }} -k ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }} --skip-duplicate
